version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ContentRatingScraper"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-u345w9wa1fd0"
s3_prefix = "ContentRatingScraper"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
